name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  md2pdf:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build md2pdf
        run: docker build -t scclouds/md2pdf:latest .

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push md2pdf
        run: DOCKER_TAG=latest make push